### ISSUE TITLE
Pinned icon in the Announcement section in main page is weird.

### ISSUE THREAD

**Issue by Jeonghyun109** [Kaist-ICLab/kaist-iclab.github.io#11]
<img width="659" alt="image" src="https://github.com/Kaist-ICLab/iclab-newhomepage/assets/65295325/f3d47079-c1dd-4fb4-9934-d017327918a5">
Its location is intended or not?

**Comment by highjun** [comment]
The pin should be left of the title.

@Jeonghyun109, please refer to some templates to pin the posts.
