### ISSUE TITLE
Project details page data generation

### ISSUE THREAD

**Issue by highjun** [Kaist-ICLab/kaist-iclab.github.io#13]
Ask PM to make an overview and image of their topic.
A project is an individual topic or group led by one of our members.
It may not be a funded government or corporate project. Also, if a funded project has too large a scope, splitting it into multiple projects is okay.

**Comment by eunkiyomi** [comment]
Currently, the representative image of each topic is only available as a thumbnail in https://homepage.iclab.dev/projects <-this page. 

How about showing these images in the project detail pages (e.g. https://homepage.iclab.dev/projects/DTx) as well?

**Comment by highjun** [comment]
* Related publications of Ours -> Use APA styles to refer venue.
* P.M. -> Leading

**Comment by highjun** [comment]
To use APA styles, use bibtex and find library to convert it to apa styles.
Furether, manage supplementary files as a json using citeKey.
