### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by gn0219** [Kaist-ICLab/kaist-iclab.github.io#15]
It already looks good, but if you want to provide more details, consider the following suggestions. These are just my personal opinions.

[Main Page]
1. Why don't you use the same font style (light/semi-light/etc.) for "Using mobile devices and wearables to provide emotional support based on context-aware computing." and "We work on sensing user behavior and contextual data through smartphones, wearables, and IoT devices." The first one looks lighter than the other.
2. Why don't you adjust the line spacing of the descriptions (sense & collect / explore & analyze / act & service) to be shorter?
3. Footer - The shadow appears unnecessary.

[Members]
1. M.S. Student order

The new design looks good. Thank you for your effort.

**Comment by highjun** [comment]
* "Using mobile ..." to Font-normal
* Line-height to 24px as [Default Feature List of Flowbite](https://flowbite.com/blocks/marketing/feature/), It seems to be changed due to Flowbite-typography
* Footer shadow 
* Sorting student in members: sort by entrance year of each program.

**Comment by highjun** [comment]
Applied. 8992a5b
