### ISSUE TITLE
Members spacing

### ISSUE THREAD

**Issue by gn0219** [Kaist-ICLab/kaist-iclab.github.io#17]
Adjust each member's container space in the mobile view.

**Comment by highjun** [comment]
@gn0219 Please make suggest appropriate spacing using Figma.

**Comment by gn0219** [comment]
See here https://www.figma.com/design/hWDvLA36u87NWRHtMF0CPS/Homepage?node-id=0-1&t=lXOAZAFIy0NA5NbN-0

**Comment by highjun** [comment]
bd18c81 Fixed!
