### ISSUE TITLE
Add TopButton for Publications page

### ISSUE THREAD

**Issue by Jeonghyun109** [Kaist-ICLab/kaist-iclab.github.io#19]
There are too many publications in the publications page.
When I scroll down, it's hard to scroll up to top.
![image](https://github.com/Kaist-ICLab/iclab-newhomepage/assets/65295325/48a3481b-95dc-4982-9621-d2fe323239ec)

I recommend to **add a TopButton**.
<img width="98" alt="image" src="https://github.com/Kaist-ICLab/iclab-newhomepage/assets/65295325/2c7d57c3-f3b3-4f42-bb60-b47015456457">
This is the reference image from Naver Commics.

**Comment by highjun** [comment]
0755597 Add Top Button
