### ISSUE TITLE
이메일 redirection 오류

### ISSUE THREAD

**Issue by Jeonghyun109** [Kaist-ICLab/kaist-iclab.github.io#2]
<img width="440" alt="image" src="https://github.com/Kaist-ICLab/iclab-newhomepage/assets/65295325/78a8b415-82ce-44b7-a747-a223ee7b623f">

이메일 아이콘 클릭 시 클립보드 복사는 되는데, 이메일 주소로 웹사이트가 이동해 404 에러 발생

**Comment by highjun** [comment]
Bug Fixed. 8a5a872
