### ISSUE TITLE
다크 모드 적용 에러 및 폰트 색상 변경 요청

### ISSUE THREAD

**Issue by gn0219** [Kaist-ICLab/kaist-iclab.github.io#26]
Publications, Members, Lectures 탭에서 다크모드 전환시 폰트 색상 변경 필요
![image](https://github.com/user-attachments/assets/c09178cf-e2ae-49c3-bf47-df3634f48076)

다크모드 적용 후 각 탭 전환시 다크모드 풀리는 에러

**Comment by highjun** [comment]
Fixed 72243c7
