### ISSUE TITLE
Update External Links to Open in a New Tab on Lab Website

### ISSUE THREAD

**Issue by Jeonghyun109** [Kaist-ICLab/kaist-iclab.github.io#32]
**Is your feature request related to a problem? Please describe the problem.**
I would prefer **links on the lab website to open in a new tab** instead of replacing the current lab page tab.

**Describe the solution you'd like**

**Describe alternatives you've considered**
Please refer to this code example.
`<a href="https://ic.kaist.ac.kr" target="_blank" rel="noopener noreferrer">link</a>`

**Additional context**
1. Blog
- notice
<img width="1034" alt="image" src="https://github.com/user-attachments/assets/c41ff10c-0fbb-47e9-b3ca-40901aef27d1">
- header
<img width="1013" alt="image" src="https://github.com/user-attachments/assets/6218af14-fd3e-434a-b8c5-e9d9f0c86d3e">

2. Course syllabus
<img width="1159" alt="image" src="https://github.com/user-attachments/assets/29c999e4-457e-4842-821c-6419ef8d856d">

3. Github profile & Google scholar
<img width="632" alt="image" src="https://github.com/user-attachments/assets/b1b78ca2-f408-4302-8088-e11e3e76af30">

**Related Issues**
None

**Comment by highjun** [comment]
@Jeonghyun109 
The newest commit solved that issue. Please check it

**Comment by Jeonghyun109** [comment]
I checked it and it worked well. Thanks!
