### ISSUE TITLE
Dark Mode Issue

### ISSUE THREAD

**Issue by thunini** [Kaist-ICLab/kaist-iclab.github.io#35]
**Describe your needs**

When the system is set into dark mode, the texts in white color are not visible.

**Reproduce**

Screenshots are shown below:

<img width="1680" alt="Screenshot 2024-11-08 at 3 53 43 PM" src="https://github.com/user-attachments/assets/c9c4b25e-1cb3-4e84-9d24-0d4be7824117">

<img width="1680" alt="Screenshot 2024-11-08 at 3 54 14 PM" src="https://github.com/user-attachments/assets/34a233d7-ab31-4dd2-830e-b132a51ce82e">

**Expected behavior**

**Please let me know the environment you opened the webpage if possible:**
- OS: macOS
- Browser: Chrome
- Version: 130.0.6723.93 (Official Build) (arm64)

**Comment by highjun** [comment]
I just removed all the dark mode feature c783923
 In other words, even though a browser is set to be dark mode, we will not give any dark mode for it.
 
@thunini Please confirm it looks okay now.
