### ISSUE TITLE
Sticky header for publication year

### ISSUE THREAD

**Issue by Jeonghyun109** [Kaist-ICLab/kaist-iclab.github.io#36]
**Is your feature request related to a problem? Please describe the problem.**
It is **confusing that the publication year isn't shown at the top of the publication page**. Even though some papers include their publication year in the conference name, I think it is still difficult to determine the publication year.
![image](https://github.com/user-attachments/assets/55d1ed82-ecfb-4cc6-8846-dcd093920b06)

**Describe the solution you'd like**
Adding sticky style for the publication year component would be better.

**Describe alternatives you've considered**
Or we can try ToC, which we considered in the past.

**Comment by highjun** [comment]
@Jeonghyun109 Thank you for your hard work!
