### ISSUE TITLE
Some pdfs are not rendered in Publication page

### ISSUE THREAD

**Issue by Jeonghyun109** [Kaist-ICLab/kaist-iclab.github.io#40]
**Describe your needs**
It can be found by googling as follows:
<img width="407" alt="image" src="https://github.com/user-attachments/assets/9699fe1f-e1b3-490d-ba24-25694be095eb">

But, there is no pdf button on the Publications page.
<img width="740" alt="image" src="https://github.com/user-attachments/assets/0504f560-914c-4921-8e0c-dc79c1207fb5">

There are other papers where pdf buttons are not rendered too, but I don't know whether they are not rendered because there is no pdf in our source code.
<img width="856" alt="image" src="https://github.com/user-attachments/assets/94387f87-e36e-4134-96ec-095897496ce8">

**Reproduce**
Screenshots are located above.

**Expected behavior**
The pdf buttons should be displayed.

**Please let me know the environment you opened the webpage if possible:**
- OS: Windows
- Browser Chrome
- Version 131.0.6778.109(공식 빌드) (64비트)

**Additional context**
-

**Comment by highjun** [comment]
9d0d4fa done.
It was because bibtex key was not matching w/ pdf.
