### ISSUE TITLE
Make ToC Component

### ISSUE THREAD

**Issue by Jeonghyun109** [Kaist-ICLab/kaist-iclab.github.io#6]
indicate current location

https://github.com/Kaist-ICLab/iclab-newhomepage/assets/65295325/428ef6e0-bb97-4c7c-b3aa-b20aa4f19908

**Comment by highjun** [comment]
Make ToC referring velog.io

**Comment by Jeonghyun109** [comment]
### Table of Contents Implementation
**Option 1. Intersection observer**
- pros: simple code, better performance (async callback)
- cons: ToC highlighting issue (not working in quick scrolling scenario)

**Option 2. Scroll event**
- pros: solve ToC highlighting issue
- cons: complex code

**Reference**
[intersection observer vs scroll event for ToC](https://velog.io/@ssoon-m/%EB%B8%94%EB%A1%9C%EA%B7%B8-%EB%AA%A9%EC%B0%A8TOC-%EB%A7%8C%EB%93%A4%EA%B8%B0-with-contentlayer-rehype)

**Comment by Jeonghyun109** [comment]
> ### Table of Contents Implementation
> **Option 1. Intersection observer**
> 
> * pros: simple code, better performance (async callback)
> * cons: ToC highlighting issue (not working in quick scrolling scenario)
> 
> **Option 2. Scroll event**
> 
> * pros: sole ToC highlighting issue
> * cons: complex code
> 
> **Reference** [intersection observer vs scroll event for ToC](https://velog.io/@ssoon-m/%EB%B8%94%EB%A1%9C%EA%B7%B8-%EB%AA%A9%EC%B0%A8TOC-%EB%A7%8C%EB%93%A4%EA%B8%B0-with-contentlayer-rehype)

@highjun Which option do you prefer?

**Comment by highjun** [comment]
페이지의 현재 위치에 맞게 조정해 주세요.
현재 2019 섹션을 보고 있는 경우 앞뒤로 2개씩, 총 5개를 표시하도록 해주시면 됩니다.

ToC의 경우, h3까지의 것만을 고려하고 짜시면 됩니다. 해당 ToC는 heading의 title, heading level, link(anchor)를 parameter로 받는다고 고려해주세요.

수고하세요!
