### ISSUE TITLE
Publication venue name

### ISSUE THREAD

**Issue by Jeonghyun109** [Kaist-ICLab/kaist-iclab.github.io#8]
<img width="892" alt="image" src="https://github.com/Kaist-ICLab/iclab-newhomepage/assets/65295325/9dcfb2c2-7dd6-448c-b680-5c440f3c5dc6">
How about inserting the name of the venue right upon the publication title UI?
I think we can make the venue UI as same as the 'publication type' UI.

**Comment by highjun** [comment]
@Jeonghyun109  Please refer some websites or templates that do what you expected.

**Comment by Jeonghyun109** [comment]
For altering option, I considered a filtering function (looks like a drop down menu).

In both cases (venue widget and venue filtering), I think **we need to manually make the abbreviation list** of every venue.
@highjun Do you think this component is necessary?

**Comment by highjun** [comment]
Discussed to not applied
